# Generated by Django 3.0.3 on 2020-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='cand_text',
            field=models.TextField(default='No Description'),
        ),
    ]
